structuretimers/urls.py
from django.conf.urls import url

from . import views

app_name = "structuretimers"

urlpatterns = [
    url(r"^$", views.timer_list, name="timer_list"),
    url(r"^add/$", views.AddTimerView.as_view(), name="add"),
    url(r"^remove/(?P<pk>\w+)$", views.RemoveTimerView.as_view(), name="delete"),
    url(r"^edit/(?P<pk>\w+)$", views.EditTimerView.as_view(), name="edit"),
    url(
        r"^list_data/(?P<tab_name>\w+)$", views.timer_list_data, name="timer_list_data"
    ),
    url(r"^get_timer_data/(?P<pk>\w+)$", views.get_timer_data, name="get_timer_data"),
    url(
        r"^select2_solar_systems/$",
        views.select2_solar_systems,
        name="select2_solar_systems",
    ),
    url(
        r"^select2_structure_types/$",
        views.select2_structure_types,
        name="select2_structure_types",
    ),
]

structuretimers/templates/structuretimers/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% trans title %}{% endblock %}

{% block content %}    
    <h2 class="text-center">{{ title }}</h2>
    <div class="col-lg-12 container">            
        {% block details %}{% endblock %}
    </div>
{% endblock %}

structuretimers/templates/structuretimers/index_button.html
{% load i18n %}
<div class="text-right">
    <a href="{% url 'structuretimers:timer_list' %}" class="btn btn-default">Back</a>
</div>

structuretimers/templates/structuretimers/timer_confirm_delete.html
{% extends "allianceauth/base.html" %}
{% load i18n %}

{% block page_title %}
    Delete Timer
{% endblock page_title %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">
            {% trans "Delete Structure Timer" %}
            {% include 'structuretimers/index_button.html' %}
        </h1>
        <div class="container-fluid">
            <div class="col-md-2 col-md-offset-5">
                <div class="row">
                    <form action="" method="post" id="confirm-delete-form">
                        {% csrf_token %}
                        <p>{% blocktrans %}Are you sure you want to delete timer "{{ object }}"?{% endblocktrans %}</p>
                        <input class="btn btn-danger btn-block" type="submit" value="Confirm" />
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

structuretimers/templates/structuretimers/timer_create_form.html
{% extends "structuretimers/timer_edit.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "Create Timer" %}
{% endblock page_title %}

{% block page_header %}
    {% trans "Create Structure Timer" %}
{% endblock %}

{% block submit_button_text %}
    {% trans "Create Timer" %}
{% endblock %}

structuretimers/templates/structuretimers/timer_edit.html
{% extends "structuretimers/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block details %}
    <div class="col-lg-12">                
        {% include 'structuretimers/index_button.html' %}
        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">                 
                    <form id="add-timer-form" class="form-signin" role="form" action="" method="POST">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        <br/>
                        <p>
                            <i class="fas fa-asterisk"></i> required fields
                        </p>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">
                            {% block submit_button_text %}
                            {% endblock %}
                        </button>
                    </form>                    
                </div>
            </div>
        </div>
    </div>

    <!-- share data with JS part -->
    <div 
        id="dataExport" 
        data-select2SolarSystemsUrl="{% url 'structuretimers:select2_solar_systems' %}" 
        data-select2StructureTypesUrl="{% url 'structuretimers:select2_structure_types' %}"> 
    </div>

{% endblock details %}

{% block extra_css %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css" rel="stylesheet" />
<link href="{% static 'structuretimers/timer_edit.css' %}" rel="stylesheet" />
{% endblock extra_css %}

{% block extra_javascript %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script type="text/javascript" src="{% static 'structuretimers/timer_edit.js' %}"></script>
{% endblock extra_javascript %}

structuretimers/templates/structuretimers/timer_list.html
{% extends "structuretimers/base.html" %}
{% load static %}
{% load i18n %}

{% block details %}                
    <div class="col-lg-12 text-center">            
        <b>{% trans "Current Eve Time:" %}</b>&nbsp;<span id="current-time">{{ current_time }}</span>
    </div>

    <span class="pull-right">
        {% if perms.structuretimers.create_timer %}
            <a 
                href="{% url 'structuretimers:add' %}" 
                class="btn btn-success" 
                title="Add new timer">
                Add Timer
            </a>
        {% endif %}
    </span>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Current Timers</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Past Timers</a></li>
    </ul>

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="tab-content">            
                <!-- current structuretimers tab -->
                <div role="tabpanel" class="tab-pane active" id="home">
                    {% include 'structuretimers/timer_list_table.html' with tab_name='current' %}
                    <p class="text-muted">
                        Timers remain on this page for {{ max_hours_expired }} hours after they expired
                    </p>
                </div>

                <!-- past structuretimers tab -->
                <div role="tabpanel" class="tab-pane" id="profile">
                    {% include 'structuretimers/timer_list_table.html' with tab_name='past' %} 
                </div>
            </div>
        </div>
    </div>
</div>

<!-- modal to show timer details -->
<div class="modal" id="modalTimerDetails" tabindex="-1" role="dialog" aria-labelledby="myModal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="gridSystemModalLabel">Timer details</h4>
            </div>                
            <div class="modal-body">
                <div id="modal_div_spinner">
                    <img class="center-block" src="{% static 'structuretimers/Spinner-1s-200px.gif' %}" alt="Spinner"/>
                </div>
                <div id="modal_div_data" style="display: none">
                    <label for="timerboardTimer">Timer</label>
                    <p><span id="timerboardTimer"></span></p>
                    <label for="timerboardImgScreenshot">Image</label>
                    <a href="#" target="_blank">
                        <img id="timerboardImgScreenshot" class="img-responsive" alt="details image" src=""/>
                    </a>
                    <br>
                    <label for="timerboardNotes">Notes</label>                    
                    <textarea id="timerboardNotes" class="form-control" rows="3" readonly></textarea>
                </div>
            </div>                
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>                    
            </div>
        </div>
    </div>


    <!-- share data with JS part -->
    <div 
        id="dataExport" 
        data-listDataCurrentUrl="{% url 'structuretimers:timer_list_data' 'current' %}" 
        data-listDataPastUrl="{% url 'structuretimers:timer_list_data' 'past' %}"
        data-getTimerDataUrl="{% url 'structuretimers:get_timer_data' 'pk_dummy' %}"
        data-titleSolarSystem="{% trans 'Solar System' %}"
        data-titleRegion="{% trans 'Region' %}"
        data-titleStructureType="{% trans 'Structure Type' %}"
        data-titleTimerType="{% trans 'Timer Type' %}"
        data-titleOwner="{% trans 'Owner' %}"
        data-titleObjective="{% trans 'Objective' %}"
        data-titleVisibility="{% trans 'Visibility' %}"        
        data-hasPermOPSEC="{{ perms.structuretimers.opsec_access }}"
        data-dataTablesPageLength="{{ data_tables_page_length }}"
        data-dataTablesPaging="{{ data_tables_paging }}"
    >
    </div>
    
{% endblock details %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'structuretimers/timer_list.css' %}" type="text/css" media="screen">    
{% endblock extra_css%}

{% block extra_javascript %}
    {% include 'bundles/moment-js.html' with locale=True %}            
    {% include 'bundles/datatables-js.html' %}        
    <script type="text/javascript" src="{% static 'js/filterDropDown/filterDropDown.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'structuretimers/timer_list.js' %}"></script>
{% endblock extra_javascript %}

structuretimers/templates/structuretimers/timer_list_table.html
{% load i18n %}
{% load humanize %}

<div class="table-responsive">    
    <table class="table table-aa table_timers" id="tab_timers_{{ tab_name }}" style="width:100%;">
        <thead>
            <tr>
                <th>{% trans "Eve Time" %}</th>
                <th>{% trans "Local Time" %}</th>
                <th>{% trans "Location" %}</th>
                <th>{% trans "Structure" %} / {% trans "Timer Type" %}</th>
                <th>{% trans "Objective" %} / {% trans "Tags" %}</th>
                <th>{% trans "Name" %} / {% trans "Owner" %}</th>
                <th>{% trans "Creator" %}</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

structuretimers/templates/structuretimers/timer_update_form.html
{% extends "structuretimers/timer_edit.html" %}
{% load i18n %}

{% block page_title %}
    {% trans "Update Structure Timer" %}
{% endblock page_title %}

{% block page_header %}
    {% trans "Update Structure Timer" %}
{% endblock %}

{% block submit_button_text %}
    {% trans "Update Structure Timer" %}
{% endblock %}